language: python

python:
  - '3.11'

dist: focal

install:
  - pip install -r src/requirements.txt

script:
  - black . --check
  - flake8 .
  - coverage run --source=src/home,src/accounts,src/public_service_finder src/manage.py test

after_success:
  - coveralls

before_deploy:
  cd src

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: us-east-1
    app: public-service-finder-dev
    env: public-service-finder-dev-env
    bucket_name: public-service-finder-dev-s3
    on:
      repo: gcivil-nyu-org/wed-fall24-team1
      branch: develop
    cleanup: false

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: us-east-1
    app: public-service-finder-prod
    env: public-service-finder-prod-env
    bucket_name: public-service-finder-prod-s3
    on:
      repo: gcivil-nyu-org/wed-fall24-team1
      branch: main
    skip_cleanup: 'true'