# Generated by Django 5.1.1 on 2024-12-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
