# Generated by Django 5.1.1 on 2024-10-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceseeker",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="serviceseeker",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
