# Generated by Django 5.1.1 on 2024-10-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_failed_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
