# Generated by Django 5.1.1 on 2024-10-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
        ("accounts", "0003_remove_customuser_failed_attempts_and_more"),
    ]

    operations = []
