# Generated by Django 5.1.1 on 2024-12-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the user's profile image stored in S3.",
                max_length=500,
                null=True,
            ),
        ),
    ]
