# Generated by Django 5.1.1 on 2024-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("user", "User"), ("service_provider", "Service Provider")],
                default="user",
                max_length=20,
            ),
        ),
    ]
