# Generated by Django 5.1.1 on 2024-12-03 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="The ID of the flagged content", max_length=255
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam or advertising"),
                            ("OFFENSIVE", "Offensive or inappropriate content"),
                            ("HARASSMENT", "Harassment or hate speech"),
                            ("MISINFORMATION", "False or misleading information"),
                            ("OTHER", "Other reason"),
                        ],
                        help_text="Primary reason for flagging",
                        max_length=20,
                    ),
                ),
                (
                    "explanation",
                    models.CharField(
                        blank=True,
                        help_text="Additional details about why this content was flagged",
                        max_length=256,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("DISMISSED", "Dismissed"),
                            ("REVOKED", "Content Revoked"),
                        ],
                        default="PENDING",
                        help_text="Current status of the flag",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When an admin reviewed this flag",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The type of content being flagged (Post, Comment, or Review)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "flagger",
                    models.ForeignKey(
                        help_text="User who created this flag",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("content_type", "object_id", "flagger")},
            },
        ),
    ]
