# Generated by Django 5.1.1 on 2024-12-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("FORUM POST", "Post"),
                    ("FORUM COMMENT", "Comment"),
                    ("REVIEW", "Review"),
                ],
                help_text="The type of content being flagged",
                max_length=20,
            ),
        ),
    ]
