# Generated by Django 5.1.1 on 2024-12-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_alter_flag_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="content_author",
            field=models.CharField(
                default="cashmere",
                help_text="Username of the content author",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flag",
            name="content_preview",
            field=models.TextField(
                default="sample", help_text="Preview/snippet of the flagged content"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flag",
            name="content_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Rating value for reviews",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flag",
            name="content_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the content (if applicable, like for posts)",
                max_length=255,
            ),
        ),
    ]
