from enum import Enum


class ServiceStatus(Enum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEACTIVATED = ""
    EDIT_REQUESTED = "EDIT_REQUESTED"
    EDIT_REJECTED = "EDIT_REJECTED"
